[package]
name = "a01_xilem_hello"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xilem = {git = "https://github.com/linebender/xilem"}
